name: fast2mine_challenge
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  get: ^4.7.2
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  sqflite: ^2.0.0+3
  path: ^1.8.3
  path_provider: ^2.0.11

dev_dependencies:
  build_runner: ^2.4.14
  json_serializable: ^6.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
  - lib/core/assets/simulacao.jsonl
  - lib/core/assets/app_icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/core/assets/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: true
    image_path: "lib/core/assets/app_icon.png"